"""PDF Generator - Race Prep Plan PDF Creation for APEX
Creates printable PDF documents for race preparation plans.

Uses fpdf2 library for clean, structured documents suitable for printing
and bringing to the track.
"""

import io

from fpdf import FPDF


class APEXPdfGenerator(FPDF):
    """Custom PDF generator for APEX Race Prep Plans.
    Extends FPDF with AGR branding and structured sections.
    """

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)

        # AGR Brand Colors (approximated for PDF)
        self.primary_color = (41, 128, 185)   # Blue
        self.accent_color = (231, 76, 60)     # Red/Orange
        self.text_color = (44, 62, 80)        # Dark blue-grey

    def header(self):
        """Custom header for each page."""
        # Logo placeholder (using text for now)
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(*self.primary_color)
        self.cell(0, 10, 'A.P.E.X.', align='L')

        # Tagline
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(*self.text_color)
        self.cell(0, 10, 'Avant Garde Racing', align='R')

        self.ln(15)
        # Divider line
        self.set_draw_color(*self.primary_color)
        self.set_line_width(0.5)
        self.line(10, 25, 200, 25)
        self.ln(5)

    def footer(self):
        """Custom footer for each page."""
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by A.P.E.X. | Page {self.page_no()}/{{nb}}', align='C')

    def add_title(self, title, subtitle=None):
        """Add main title section."""
        self.set_font('Helvetica', 'B', 24)
        self.set_text_color(*self.text_color)
        self.multi_cell(0, 12, title, align='C')

        if subtitle:
            self.set_font('Helvetica', '', 14)
            self.set_text_color(128, 128, 128)
            self.multi_cell(0, 8, subtitle, align='C')

        self.ln(10)

    def add_section_header(self, title):
        """Add a section header with styling."""
        self.ln(5)
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(*self.accent_color)
        self.cell(0, 10, title, ln=True)

        # Underline
        self.set_draw_color(*self.accent_color)
        self.set_line_width(0.3)
        current_y = self.get_y()
        self.line(10, current_y, 100, current_y)
        self.ln(3)

        # Reset text color
        self.set_text_color(*self.text_color)

    def add_paragraph(self, text):
        """Add a paragraph of text."""
        self.set_font('Helvetica', '', 11)
        self.set_text_color(*self.text_color)
        self.multi_cell(0, 6, text)
        self.ln(3)

    def add_bullet_list(self, items):
        """Add a bulleted list."""
        self.set_font('Helvetica', '', 11)
        self.set_text_color(*self.text_color)

        for item in items:
            # Bullet point
            self.cell(10, 6, chr(149), align='R')  # Bullet character
            self.multi_cell(0, 6, f" {item}")

    def add_checklist(self, items, checked=None):
        """Add a checklist with checkboxes for printing.

        Args:
            items: List of checklist items
            checked: Optional set/list of indices that should be pre-checked

        """
        checked = checked or set()
        self.set_font('Helvetica', '', 11)
        self.set_text_color(*self.text_color)

        for i, item in enumerate(items):
            # Checkbox (empty square or checked)
            box_char = chr(9745) if i in checked else chr(9744)  # Ballot box
            self.cell(10, 7, box_char, align='R')
            self.multi_cell(0, 7, f" {item}")

    def add_setup_table(self, setup_dict, title="Setup Parameters"):
        """Add a formatted table for the 24-parameter setup.

        Args:
            setup_dict: Dictionary of setup parameters
            title: Table title

        """
        self.add_section_header(title)

        # Define column widths
        col_width = 45
        row_height = 7

        self.set_font('Helvetica', 'B', 10)

        # Group parameters by category
        categories = {
            "Differentials": ['DF', 'DC', 'DR'],
            "Front Suspension": ['SO_F', 'SP_F', 'SB_F', 'P_F', 'Toe_F', 'RH_F', 'C_F'],
            "Rear Suspension": ['SO_R', 'SP_R', 'SB_R', 'P_R', 'Toe_R', 'RH_R', 'C_R'],
            "Tires": ['Tread', 'Compound'],
            "Power": ['Venturi', 'Pipe', 'Clutch', 'Bell', 'Spur']
        }

        for cat_name, params in categories.items():
            # Category header
            self.set_fill_color(*self.primary_color)
            self.set_text_color(255, 255, 255)
            self.set_font('Helvetica', 'B', 9)
            self.cell(0, row_height, cat_name, ln=True, fill=True)

            # Parameters
            self.set_text_color(*self.text_color)
            self.set_font('Helvetica', '', 9)

            row_params = []
            for param in params:
                value = setup_dict.get(param, '-')
                row_params.append(f"{param}: {value}")

                # Print row when we have 4 items or at the end
                if len(row_params) == 4 or param == params[-1]:
                    for rp in row_params:
                        self.cell(col_width, row_height, rp, border=1)
                    self.ln()
                    row_params = []

        self.ln(5)

    def add_key_value_section(self, data, title=None):
        """Add a section with key-value pairs.

        Args:
            data: Dict of key-value pairs
            title: Optional section title

        """
        if title:
            self.add_section_header(title)

        self.set_font('Helvetica', '', 11)
        col_width = 95

        for key, value in data.items():
            self.set_font('Helvetica', 'B', 10)
            self.cell(50, 7, f"{key}:")
            self.set_font('Helvetica', '', 10)
            self.multi_cell(col_width, 7, str(value))

    def add_contingency_box(self, condition, action):
        """Add a styled contingency box (If X, then Y).

        Args:
            condition: The "if" condition
            action: The "then" action

        """
        # Box background
        self.set_fill_color(245, 245, 245)
        self.set_draw_color(*self.primary_color)

        start_y = self.get_y()
        self.rect(10, start_y, 190, 20, style='DF')

        # Content
        self.set_xy(15, start_y + 3)
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(*self.accent_color)
        self.cell(15, 6, "IF:")
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*self.text_color)
        self.multi_cell(170, 6, condition)

        self.set_x(15)
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(*self.primary_color)
        self.cell(15, 6, "THEN:")
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*self.text_color)
        self.multi_cell(170, 6, action)

        self.ln(5)


def generate_race_prep_plan(
    racer_name,
    event_name,
    track_name,
    event_date,
    vehicle_info,
    strategic_overview,
    track_intelligence,
    recommended_setup,
    mechanical_checklist,
    parts_list,
    practice_strategy,
    contingencies
):
    """Generate a complete Race Prep Plan PDF.

    Args:
        racer_name: Driver name
        event_name: Event/session name
        track_name: Track name
        event_date: Date of event
        vehicle_info: Dict with brand, model
        strategic_overview: String with goals and expectations
        track_intelligence: String with track-specific knowledge
        recommended_setup: Dict of 24 setup parameters
        mechanical_checklist: List of maintenance items
        parts_list: List of parts/consumables to bring
        practice_strategy: List of practice session focus items
        contingencies: List of dicts with 'condition' and 'action' keys

    Returns:
        bytes - PDF file content

    """
    pdf = APEXPdfGenerator()
    pdf.alias_nb_pages()
    pdf.add_page()

    # Title
    pdf.add_title(
        f"Race Prep Plan: {event_name}",
        f"{track_name} | {event_date}"
    )

    # Event Info
    pdf.add_key_value_section({
        "Driver": racer_name,
        "Vehicle": f"{vehicle_info.get('brand', 'N/A')} {vehicle_info.get('model', 'N/A')}",
        "Track": track_name,
        "Date": str(event_date)
    })

    # Strategic Overview
    pdf.add_section_header("1. Strategic Overview")
    pdf.add_paragraph(strategic_overview)

    # Track Intelligence
    pdf.add_section_header("2. Track Intelligence")
    pdf.add_paragraph(track_intelligence)

    # Recommended Starting Setup
    if recommended_setup:
        pdf.add_page()
        pdf.add_setup_table(recommended_setup, "3. Recommended Starting Setup")

    # Mechanical Checklist
    pdf.add_section_header("4. Pre-Race Mechanical Checklist")
    if mechanical_checklist:
        pdf.add_checklist(mechanical_checklist)
    else:
        pdf.add_paragraph("No specific maintenance items identified.")

    # Parts & Consumables
    pdf.add_section_header("5. Parts & Consumables to Bring")
    if parts_list:
        pdf.add_bullet_list(parts_list)
    else:
        pdf.add_paragraph("Standard pit kit should suffice.")

    # Practice Strategy
    pdf.add_page()
    pdf.add_section_header("6. Practice Session Strategy")
    if practice_strategy:
        for i, strategy in enumerate(practice_strategy, 1):
            pdf.add_paragraph(f"Session {i}: {strategy}")
    else:
        pdf.add_paragraph("Focus on baseline verification, then tuning progression.")

    # Contingency Notes
    pdf.add_section_header("7. Contingency Plans")
    if contingencies:
        for contingency in contingencies:
            pdf.add_contingency_box(
                contingency.get('condition', 'Conditions change'),
                contingency.get('action', 'Adjust accordingly')
            )
    else:
        pdf.add_paragraph("Be prepared to adapt to changing conditions.")

    # Final notes
    pdf.add_page()
    pdf.add_section_header("Notes")
    pdf.add_paragraph("Use this space for additional observations during the event:")
    pdf.ln(50)  # Space for handwritten notes

    # Generate PDF bytes
    output = io.BytesIO()
    pdf.output(output)
    return output.getvalue()


# Quick test function
def _test_pdf():
    """Generate a test PDF to verify the generator works."""
    pdf_bytes = generate_race_prep_plan(
        racer_name="Test Racer",
        event_name="Thunder Alley Challenge",
        track_name="Thunder Alley RC",
        event_date="2025-01-15",
        vehicle_info={"brand": "Tekno", "model": "NB48 2.2"},
        strategic_overview="This is a test event. Goals: 1) Validate baseline 2) Tune for high traction 3) Aim for top 5 in A-main.",
        track_intelligence="Thunder Alley typically runs high traction by Sunday. The layout favors nimble cars with good corner exit.",
        recommended_setup={
            "DF": 7000, "DC": 5000, "DR": 3000,
            "SO_F": 350, "SP_F": "3.4", "SB_F": 2.3, "P_F": "1.2x4",
            "Toe_F": -1.0, "RH_F": 27.0, "C_F": -2.0,
            "SO_R": 400, "SP_R": "3.6", "SB_R": 2.5, "P_R": "1.7x4",
            "Toe_R": 3.0, "RH_R": 28.0, "C_R": -3.0,
            "Tread": "Reflex", "Compound": "Green",
            "Venturi": 7.0, "Pipe": "REDS 2143", "Clutch": "4-Shoe Med",
            "Bell": 13, "Spur": 48
        },
        mechanical_checklist=[
            "Rebuild front shocks (new seals, fresh 350cst oil)",
            "Check diff oils - service if over 3 hours run time",
            "Inspect all turnbuckles for bending",
            "Verify clutch shoes and springs",
            "Check all screws for looseness"
        ],
        parts_list=[
            "Green compound tires (4 sets)",
            "Aqua compound tires (2 sets - backup)",
            "350cst and 400cst shock oil",
            "Spare wing",
            "Extra wheel nuts and axle pins"
        ],
        practice_strategy=[
            "Baseline verification - stock setup, 2-3 laps for comfort",
            "Tire compound test - compare Green vs Aqua",
            "Diff tuning - try 5k vs 7k front diff",
            "Final race simulation - push pace, evaluate consistency"
        ],
        contingencies=[
            {"condition": "Track is wetter than expected", "action": "Switch to Aqua compound, add 500cst to front diff"},
            {"condition": "Track is drier/higher traction than expected", "action": "Soften front springs, reduce front camber"}
        ]
    )

    with open("test_race_prep.pdf", "wb") as f:
        f.write(pdf_bytes)
    print("Test PDF generated: test_race_prep.pdf")


if __name__ == "__main__":
    _test_pdf()
